apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: adarshtripathi1/backend-chat
          ports:
            - containerPort: 8082
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: MGUSER
              value: mongodb
            - name: MGHOST
              value: mongodb-cluster-ip-service
            - name: MGPORT
              value: '27017'
            - name: MONGO
              value: mongodb://mongodb-cluster-ip-service:27017/BChat
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim